// Auto-generated by pcnn_jax.py -- PCNN dimensions & constants
#ifndef PCNN_CONFIG_H
#define PCNN_CONFIG_H

#define N_FEAT   6
#define IN_NN    32
#define LSTM_H   128
#define LSTM_L   3
#define OUT_NN   32

#define COL_OUT  0
#define COL_SOL  1
#define COL_OCC  2
#define COL_T    3
#define COL_P    4
#define COL_CASE 5

#define DIV_FACTOR   30.0f
#define ZERO_POWER   4.613306710e-01f
#define ROOM_MIN     9.937950033e+00f
#define ROOM_DIFF    2.091399694e+01f
#define OUT_MIN      -1.390000000e+01f
#define OUT_DIFF     5.060000000e+01f
#define A_EFF        3.723846748e-02f
#define B_EFF        1.254414674e-04f
#define D_EFF        4.468457773e-02f

// raw-data min/max per column, for host-side normalization
// col 0: Outdoor air temperature [C]
// col 1: Solar radiation [W/m2]
// col 2: Occupant count
// col 3: Room temperature [C]
// col 4: HVAC load [W]
// col 5: Case
static const float RAW_MIN[6] = { -1.390000000e+01f, 0.000000000e+00f, 7.256700000e-01f, 9.937950033e+00f, -4.458769731e+03f, -1.000000000e+00f };
static const float RAW_MAX[6] = { 3.670000000e+01f, 9.430000000e+02f, 3.000000000e+00f, 3.085194697e+01f, 5.413117909e+03f, 1.000000000e+00f };
#endif
