#!/usr/bin/env python3
"""
Export a *real* PCNN checkpoint (trained with the PCNN-Comparison repo) to the
HLS headers. Run this on the machine where you train, from the repo root:

    python3 export_weights_pytorch.py \
        --ckpt <path to best_model.pt> \
        --csv  "Processed E+ data/Mid.csv" \
        --out  ../pcnn_zcu102/hls/weights

It reproduces the exact preprocessing of pcnn_epfl (min-max to [0.1,0.9],
zero_power, parameter scalings) and writes pcnn_weights.h / pcnn_config.h in
the same format as pcnn_jax.py, plus golden test vectors via the PyTorch model.
"""
import argparse, os
import numpy as np
import pandas as pd
import torch

INTERVAL = 15
WARM, SEQ = 8, 96
IN_NN, H, L, OUT_NN = 32, 128, 3, 32   # paper Table 6
DIV = 30.0
X_COLS = ['Outdoor air temperature [C]', 'Solar radiation [W/m2]',
          'Occupant count', 'Room temperature [C]', 'HVAC load [W]']
COLS = dict(OUT=0, SOL=1, OCC=2, T=3, P=4, CASE=5)

def consts_from_csv(csv):
    d = pd.read_csv(csv, index_col=0)
    df = d[X_COLS].copy()
    case = np.full(len(df), -1.0)
    case[d['HVAC load [W]'].values == 0] = 0.0
    case[d['HVAC load [W]'].values > 0] = 1.0
    df['Case'] = case
    mn, mx = df.min(), df.max()
    diffT = float(mx[X_COLS[3]] - mn[X_COLS[3]]); minT = float(mn[X_COLS[3]])
    diffO = float(mx[X_COLS[0]] - mn[X_COLS[0]]); minO = float(mn[X_COLS[0]])
    diffP = float(mx[X_COLS[4]] - mn[X_COLS[4]]); minP = float(mn[X_COLS[4]])
    zero_power = 0.8 * (0.0 - minP) / diffP + 0.1
    b_scal = 1.0 / (1.5 / diffT * 0.8 / 25 / 6 / 60 * INTERVAL)
    a_scal = 1.0 / (2.0 / diffT * 0.8 / (1000.0 / diffP * 0.8) / (4 * 60 / INTERVAL))
    norm = 0.8 * (df - mn) / (mx - mn) + 0.1
    X = norm.values[:-1].astype(np.float32)
    Y = norm['Room temperature [C]'].values[1:].astype(np.float32)
    return dict(diffT=diffT, minT=minT, diffO=diffO, minO=minO,
                zero_power=zero_power, a_scal=a_scal, b_scal=b_scal,
                d_scal=a_scal, mins=mn.values, maxs=mx.values,
                cols=list(df.columns)), X, Y

def carr(f, name, arr):
    arr = np.asarray(arr, np.float64).ravel()
    f.write(f'static const float {name}[{len(arr)}] = {{\n')
    for i in range(0, len(arr), 6):
        f.write('    ' + ', '.join(f'{x:.9e}f' for x in arr[i:i + 6]) + ',\n')
    f.write('};\n\n')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt', required=True)
    ap.add_argument('--csv', required=True)
    ap.add_argument('--out', required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    consts, X, Y = consts_from_csv(args.csv)

    ck = torch.load(args.ckpt, map_location='cpu', weights_only=False)
    sd = ck['model_state_dict'] if 'model_state_dict' in ck else ck
    g = lambda k: sd[k].detach().numpy()

    with open(os.path.join(args.out, 'pcnn_weights.h'), 'w') as f:
        f.write('// Auto-generated by export_weights_pytorch.py\n')
        f.write('#ifndef PCNN_WEIGHTS_H\n#define PCNN_WEIGHTS_H\n\n')
        carr(f, 'W_IN', g('input_nn.0.0.weight'))
        carr(f, 'B_IN', g('input_nn.0.0.bias'))
        for l in range(L):
            carr(f, f'LSTM_WIH{l}', g(f'lstm.weight_ih_l{l}'))
            carr(f, f'LSTM_WHH{l}', g(f'lstm.weight_hh_l{l}'))
            carr(f, f'LSTM_BIH{l}', g(f'lstm.bias_ih_l{l}'))
            carr(f, f'LSTM_BHH{l}', g(f'lstm.bias_hh_l{l}'))
        carr(f, 'LN_G', g('norm.weight')); carr(f, 'LN_B', g('norm.bias'))
        carr(f, 'W_OUT1', g('output_nn.0.0.weight'))
        carr(f, 'B_OUT1', g('output_nn.0.0.bias'))
        carr(f, 'W_OUT2', g('output_nn.1.0.weight'))
        carr(f, 'B_OUT2', g('output_nn.1.0.bias'))
        carr(f, 'INIT_H', g('initial_h')); carr(f, 'INIT_C', g('initial_c'))
        f.write('#endif\n')

    a_eff = float(np.exp(g('a.log_weight'))) / consts['a_scal']
    b_eff = float(np.exp(g('b.log_weight'))) / consts['b_scal']
    d_eff = float(np.exp(g('d.log_weight'))) / consts['d_scal']
    with open(os.path.join(args.out, 'pcnn_config.h'), 'w') as f:
        f.write('// Auto-generated by export_weights_pytorch.py\n')
        f.write('#ifndef PCNN_CONFIG_H\n#define PCNN_CONFIG_H\n\n')
        f.write(f'#define N_FEAT   6\n#define IN_NN    {IN_NN}\n')
        f.write(f'#define LSTM_H   {H}\n#define LSTM_L   {L}\n')
        f.write(f'#define OUT_NN   {OUT_NN}\n\n')
        for k, v in COLS.items():
            f.write(f'#define COL_{k}{" "*(4-len(k))} {v}\n')
        f.write(f'\n#define DIV_FACTOR   {DIV}f\n')
        f.write(f'#define ZERO_POWER   {consts["zero_power"]:.9e}f\n')
        f.write(f'#define ROOM_MIN     {consts["minT"]:.9e}f\n')
        f.write(f'#define ROOM_DIFF    {consts["diffT"]:.9e}f\n')
        f.write(f'#define OUT_MIN      {consts["minO"]:.9e}f\n')
        f.write(f'#define OUT_DIFF     {consts["diffO"]:.9e}f\n')
        f.write(f'#define A_EFF        {a_eff:.9e}f\n')
        f.write(f'#define B_EFF        {b_eff:.9e}f\n')
        f.write(f'#define D_EFF        {d_eff:.9e}f\n\n')
        f.write('static const float RAW_MIN[6] = { ' +
                ', '.join(f'{x:.9e}f' for x in consts['mins']) + ' };\n')
        f.write('static const float RAW_MAX[6] = { ' +
                ', '.join(f'{x:.9e}f' for x in consts['maxs']) + ' };\n')
        f.write('#endif\n')

    # golden vectors with the PyTorch module itself
    import sys
    sys.path.insert(0, '.')
    from pcnn_epfl.module import PCNN
    model = PCNN(device='cpu', inputs_D=[1, 2], learn_initial_hidden_states=True,
                 feed_input_through_nn=True, input_nn_hidden_sizes=[IN_NN],
                 lstm_hidden_size=H, lstm_num_layers=L, layer_norm=True,
                 output_nn_hidden_sizes=[OUT_NN], case_column=5,
                 temperature_column=[3], out_column=0, neigh_column=[],
                 power_column=[4], zero_power=np.array([consts['zero_power']]),
                 division_factor=[DIV],
                 normalization_variables={
                     'Room': [torch.tensor([consts['minT']]), torch.tensor([consts['diffT']])],
                     'Neigh': [torch.tensor([]), torch.tensor([])],
                     'Out': [torch.tensor([consts['minO']]), torch.tensor([consts['diffO']])]},
                 parameter_scalings={'a': [consts['a_scal']], 'b': [consts['b_scal']],
                                     'c': [consts['b_scal'] / 10], 'd': [consts['d_scal']]})
    model.load_state_dict(sd)
    model.get_intermediate = True
    model.eval()
    s = 211 * 96
    xseq = torch.tensor(X[s:s + SEQ]).unsqueeze(0)   # (1, SEQ, 6)
    Ts, Ds, Es = [], [], []
    states = None
    with torch.no_grad():
        for t in range(SEQ):
            T, D, E, states = model(xseq[:, t, :], states, warm_start=t < WARM)
            Ts.append(float(T)); Ds.append(float(D)); Es.append(float(E))
    np.savetxt(os.path.join(args.out, 'tb_x.txt'), X[s:s + SEQ], fmt='%.9e')
    np.savetxt(os.path.join(args.out, 'tb_ref.txt'),
               np.stack([Ts, Ds, Es], 1), fmt='%.9e')
    np.savetxt(os.path.join(args.out, 'tb_y.txt'), Y[s:s + SEQ], fmt='%.9e')
    print('export complete ->', args.out)

if __name__ == '__main__':
    main()
