#!/usr/bin/env python3
"""Convert hls/tb_data (tb_x.txt, tb_ref.txt) into vitis/demo_sequence.h."""
import sys, numpy as np
d = sys.argv[1] if len(sys.argv) > 1 else 'hls/tb_data'
X = np.loadtxt(f'{d}/tb_x.txt'); R = np.loadtxt(f'{d}/tb_ref.txt')
print('// Auto-generated by make_demo_header.py')
print('#ifndef DEMO_SEQUENCE_H\n#define DEMO_SEQUENCE_H')
print(f'static const float DEMO_X[{X.shape[0]}][6] = {{')
for r in X:
    print('  { ' + ', '.join(f'{v:.9e}f' for v in r) + ' },')
print('};')
print(f'static const float DEMO_REF[{R.shape[0]}] = {{')
for i in range(0, len(R), 6):
    print('  ' + ', '.join(f'{v:.9e}f' for v in R[i:i+6, 0]) + ',')
print('};\n#endif')
