#!/usr/bin/env python3
"""
Convert Harvard-generated test vectors (tb_x.txt + tb_y.txt) into
vitis/demo_sequence.h for bare-metal testing on the ZCU102.

Usage:
    python make_harvard_header.py ../../out/5.417_tb_x.txt ../../out/5.417_tb_y.txt \
        --horizons 1 --start 0 > ../vitis/demo_sequence.h
python3 make_harvard_header.py \
    ../../out/5.417_tb_x.txt ../../out/5.417_tb_y.txt \
    --horizons 195 > ../vitis/demo_sequence.h

    --horizons N   number of 96-step horizons to embed (default: 1)
    --start    H   which horizon index to start from   (default: 0)

The generated header defines:
    DEMO_HORIZONS   number of horizons embedded
    DEMO_SEQ        total number of steps (horizons * 96)
    DEMO_X[DEMO_SEQ][6]  normalized inputs
    DEMO_REF[DEMO_SEQ]   ground-truth normalized T_room (next step)
"""
import argparse, sys
import numpy as np

HORIZON = 96

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tb_x", help="path to tb_x.txt (6 columns)")
    ap.add_argument("tb_y", help="path to tb_y.txt (1 column, ground-truth T_room)")
    ap.add_argument("--horizons", type=int, default=1,
                    help="number of 96-step horizons to embed (default: 1)")
    ap.add_argument("--start", type=int, default=0,
                    help="horizon index to start from (default: 0)")
    args = ap.parse_args()

    X = np.loadtxt(args.tb_x)
    Y = np.loadtxt(args.tb_y)

    total_horizons = len(X) // HORIZON
    print(f"// tb_x has {len(X)} steps = {total_horizons} horizons", file=sys.stderr)

    end_h = min(args.start + args.horizons, total_horizons)
    if args.start >= total_horizons:
        print(f"ERROR: --start {args.start} but only {total_horizons} horizons available",
              file=sys.stderr)
        sys.exit(1)

    start_idx = args.start * HORIZON
    end_idx = end_h * HORIZON
    n_horizons = end_h - args.start
    n_steps = n_horizons * HORIZON

    Xsel = X[start_idx:end_idx]
    Ysel = Y[start_idx:end_idx]

    print(f"// Embedding horizons {args.start}..{end_h-1} "
          f"({n_horizons} horizons, {n_steps} steps)", file=sys.stderr)

    # ---- emit header ----
    print("// Auto-generated by make_harvard_header.py")
    print("#ifndef DEMO_SEQUENCE_H")
    print("#define DEMO_SEQUENCE_H")
    print(f"#define DEMO_HORIZONS {n_horizons}")
    print(f"#define DEMO_SEQ {n_steps}")
    print(f"static const float DEMO_X[{n_steps}][6] = {{")
    for r in Xsel:
        print("  { " + ", ".join(f"{v:.9e}f" for v in r) + " },")
    print("};")
    print(f"static const float DEMO_REF[{n_steps}] = {{")
    for i in range(0, len(Ysel), 6):
        chunk = Ysel[i : i + 6]
        print("  " + ", ".join(f"{v:.9e}f" for v in chunk) + ",")
    print("};")
    print("#endif")


if __name__ == "__main__":
    main()
